{include file="header.tpl.php"}







<!--Contents-->

<div class="clear page_contents_wrapper">



<div class="gap20px">&nbsp;</div>



<h3 class="heading">Terms Of Service</h3>





<p>

This Terms of Service Agreement (the "Agreement") describes the terms and conditions on which Our Site ("we" or "Company") offer services to you ("user" or "You"). By registering for or using Website services, User agrees to be bound by the following terms and conditions. You should carefully read the following Terms of Service Agreement before using the website ("Site") and our services ("Services").This is a legally binding agreement. By using the Site or any Services provided in connection with the Site, you agree to abide by these Terms of Use, as they may be amended by Our Site from time to time in its sole discretion and without specific notice to you. It is your responsibility to review these Terms of Use periodically, and if at any time you find these Terms of Use unacceptable, you must immediately leave the Site and cease all use of the Service and the Site. This Agreement constitutes the entire and only agreement between us and you, and supersedes all prior agreements, representations, warranties and understandings with respect to the Site, the content, products or services provided by or through the Site, and the subject matter of this Agreement.
  <p>
1. The right to use Website services. Our Services are available only to individuals and business entities (including but not limited to sole proprietorships) in good legal standing that can form legally binding contracts under applicable law. User hereby represents and warrants that it is duly licensed to do business and is in good legal standing in the jurisdictions in which it does business (during the term of this Agreement) that it is not a business rival of Website, and that the person accepting this this Agreement for user is at least eighteen years of age and otherwise capable of and authorized to enter binding contracts for user.
  <p>
2. Website Services. Subject to the terms and conditions of this Agreement, Website makes certain Services available to the User. For the purposes of this Agreement: (a) "user" (or "you") means the individual or business entity that is using or registering to use the Services, including its employees and agents; (b) Website "Services" means those electronic or interactive services offered by Website. Website reserves the right to modify, suspend or discontinue, temporarily or permanently any of the Services at any time, in its own sole discretion.
   <p>
3. Materials and Trademarks You acknowledge that all materials (except those uploaded by users) provided on this Web site, including but not limited to information, documents, products, logos, graphics, sounds, images, software, and services (collectively "Materials"), are provided either by Website or by their respective third party authors, developers and vendors (collectively "Third Party Providers") and the underlying intellectual property rights are owned by Website and/or its Third Party Providers. Elements of the Web site are protected by trade dress and other laws and may not be copied or imitated in whole or in part. Website, the Website logo and other Website products referenced herein are trademarks of Website, and may be registered in certain jurisdictions. All other product names, company names, marks, logos, and symbols may be the trademarks of their respective owners.
    <p>
4. User Information. Upon registration User agrees that has not previously registered an account with our Services and that email address and personal information are valid. User represents and warrants that the information it provides in Website contact information forms is true, accurate, current and complete. User agrees to maintain and update this information to ensure that it is true, accurate, current, complete, and to provide proof of identification upon request. If, at any time, any information provided by User is untrue, inaccurate, not current or incomplete, Website will have the right to suspend or terminate Users account and present Agreement.
     <p>
5. User Account. Authorized Users: User may designate persons to act as its agents to use the Services, provided that each designated person has the legal capacity to enter into binding contracts for User. Furthermore, User represents and warrants that each person who registers under Users account is an authorized agent of User (an "Authorized User") who has such legal capacity. Responsibility for Access: User is the unique legal owner for the data of the account (the login, password and all attendant data). User is solely responsible and liable for any and all access to and use of the Services (including all activities and transactions) by any Authorized User and/or User ID registered under Users account. It is Users responsibility, through its systems administrator Authorized User, to set the appropriate access for each of Users Authorized Users. Responsibility for User IDs and Passwords: User is solely responsible for maintaining the confidentiality of User access information, i.e. account IDs and passwords of its Authorized Users, and are responsible for all activities and transactions that occur under your account. Website does not take any responsibility for monetary losses incurred by a breach in Users account by a third party. Notification of Unauthorized Use: User will immediately notify Website if User notices any activity indicating that Users account or data is being used without authorization, including, User becomes aware of any unauthorized use of any product or service related to its account.
      <p>
6. User Data. User has sole responsibility and liability for the data you store on Websites servers. User controls its data through its generated link. Website encourages User to archive its data regularly and frequently; User bears full responsibility for archiving its data and sole liability for any lost or irrecoverable data. User agrees to maintain its data in compliance with its legal obligations. Website will delete User data upon termination of this Agreement. However, Website may retain User data in its archives after deletion and will not be liable to User in any way for such retained data. We may communicate with users from time to time via email to send information about important changes to our products and services, and to send notices and other disclosures required by law. By providing your email address, you agree to these communications, but they will be primarily informational in nature rather than promotional and will be strictly limited in number. We follow a strict no-spam policy. Website will provide access to the Services and Users data to an agent of User ("Authorized Agent") who provides Website with a notarized letter signed by an officer of User which letter shall include statements of authenticity, authority, and liability as required by Website in its sole discretion. User expressly and irrevocably agrees that Website may rely on such a letter and on the apparent authority of the person requesting access to the Services or to Users account. In no event will Website be liable to User or any third party for Websites reliance on such letter or such apparent authority.
       <p>
7. General Prohibitions. Users will be permanently banned and earnings revoked if: Upload any form of child exploitation/pornography Upload any materials that are in any way sexually explicit Upload any materials that pertain to and/or promote pornography Promote any type of file on pages that contain sexually explicit, copyrighted, or otherwise illegal content Upload adult files, nudity, semi-nudity, suggestive images/videos, sexual filenames or anything remotely adult-related. Download your own files continuously, download anothers file, offer cash incentives to downloaders, coax others into continuously downloading your own file, obtain downloads in an illicit manner such as, but not limited to, an automated bot, or register more than one account. Abuse our services to coerce users into registering on other websites. Exchange download links with other affiliates, download other affiliates files in order to receive downloads, or offer a form of points to the downloader for a download. Post Website download links on 4chan.org. Purchase a Premium Account through own download link. Instruct or encourage any download to use a method to bypass our surveys or enter fake information. Download own files, with or without a Proxy. Upload files that are fake or counterfeit. Creating multiple accounts for one user. If we find such accounts they will be deleted and earnings revoked. Sharing premium accounts (multiple users of one premium account). Send unsolicited email, junk mail, spam, chain letters, or promotions or advertisements for products or services. Harm or threaten to harm other users in any way or interfere with, or attempt to interfere with, the access of any user, host or network, including without limitation, by sending a virus, overloading, flooding, spamming, or mail-bombing the Service. Impersonate or misrepresent your affiliation with any person or entity. Upload or transmit any User file: 1) that you do not have the lawful right to copy, transmit, distribute, and display (including any User files that would violate any confidentiality or fiduciary obligations that you might have with respect to the User files), 2) for which you do not have the consent or permission of each identifiable person in the User files to use the name, voice, signature, photograph, or likeness of each such person (to the extent each is implicated by the User files), 3) that infringes or misappropriates the intellectual property rights or violates the privacy rights of any third party (including without limitation copyright, trademark, patent, trade secret, or other intellectual property right, or moral right or right of publicity), 4) that is false or misleading, 5) that is defamatory, 6) that is obscene, pornographic, or offensive and 7) that promotes bigotry, racism, hatred, or harm against any individual or group and 8) that violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability.
 <p>
8. Acceptable Use You agree to NOT use Websites Service to: Upload, post, e-mail, transmit or otherwise make available any Content that spreads messages of terror or depicts torture or death images, if appropriate, the content will be reported to the appropriate legal authority and/or the members ISP will be contacted; Harm minors in any way, this includes any form of child pornography; if appropriate, the content will be reported to the relevant legal authority and/or the members ISP will be contacted; upload, post, e-mail, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party. On this matter, please refer to Websites DMCA Policy, which is herein incorporated by reference.
  <p>
8.1 Illegal Actions/Content. Website neither sanctions nor permits site content or the transmission of data that contains illegal or obscene material or fosters or promotes illegal activity, including but not limited to, gambling, the offering for sale of illegal weapons, and the promotion or publication of any material that may violate hate crimes legislation. In the case of the non-observance of the present requirements, Website reserves the right to immediately suspend or terminate any account or transmission that violates this policy, without prior notice. User will not commit or permit wrongful or damaging acts which justify civil action including, but not limited to, posting of defamatory, scandalous, or private information about a person without their consent or intentionally inflicting emotional distress. Further, should User violate this policy, Website will actively assist and cooperate with law enforcement agencies and government authorities in collecting and tendering information about User, Users site, the illegal or obscene content, and those persons that may have inappropriately accessed, acquired, or used the illegal or obscene content. Illegal actions also include intrusions or attempts of intrusion into the information system of , or attempts to affect the ability of to render Services.
 <p>
These are (but not limited to the following actions): Unauthorized access to or use of Website Services, including any attempt to probe, scan or test the vulnerability of a system or to breach security or authentication measures without express authorization of Website b) Interference with Service to any User or network including, without limitation, flooding, or deliberate attempts to overload a system and broadcast attacks c) Use of any device, software, or routine to interfere or attempt to interfere with the proper working of the Services d) Any action that imposes an unreasonable or disproportionately large load on Websites infrastructure Customer shall not decompile, disassemble, decrypt, extract, reverse engineer or otherwise attempt to derive the source code of the "software tools" (including the tools, methods, processes, and infrastructure) underlying the Services or any other software on the Website Web site. There are many other actions that can affect negatively the infrastructure of , which are strictly prohibited and are the subject of criminal and civil liability.
 <p>
8.2 Child Exploitation Website will cooperate fully with any criminal investigation into a Users violation of any act of law concerning child exploitation, including child pornography. Website will involve and cooperate with law enforcement if a criminal violation is suspected. This may result in disclosing all information available to Website including but not limited to information contained in Users profiles, folders, transmissions, communications or any other information Website considers applicable. Any user involved in such file transfers through Website will also be permanently removed from our service. In case of using Website Service for distribution of the files containing materials which appear to involve child exploitation, the account of the user who placed such files will be immediately deleted and all neccessary information will be passed on to the National Center for Missing & Exploited Children as well as to the administrative tribunals and/or members of the ISP. Complaints of the persons, breaking our Rules, are accepted by way of posting via the abuse form Each complaint will be considered, and depending on the results, can lead to the deletion of the Users account without preliminary prevention.
 <p>
8.3 Copyright or Trademark Infringement Website Services may be used only for lawful purposes. Transmission, distribution or storage of any material in violation of any applicable law or regulation, including export control laws, is prohibited. This includes, without limitation, material protected by patent, copyright, trademark, service mark, trade secret or other intellectual property rights. If you use another partys material, you must obtain prior authorization. By using the Services, you represent and warrant that you are the author and copyright owner and/or proper licensee with respect to any hosted content and you further represent and warrant that no content violates the trademark or rights of any third party. Website reserves the right to suspend or terminate a Users transmission(s) that, in Websites discretion, violates these policies or violates any law or regulation.
 <p>
8.4 DMCA Compliance Although Website is a United States registered entity, and does assent to, and submit to jurisdiction in the United States, Website seeks to protect and enforce the rights of copyright holders around the world. Therefore, Website seeks to comply with the Digital Millennium Copyright Act of the United States, 17 U.S.C. ? 512 ("DMCA") and its take down provisions. Website, in its sole and absolute discretion, may take any reasonably necessary measures to terminate Users who infringe the intellectual property rights of others. Website reserves the right to remove, delete, or deny access to materials, data, or files which Website, in good faith, has determined to be infringing material. If you believe that a user of the site has infringed your intellectual property rights, please notify Websites Copyright Agent, and provide the following information: A physical or electronic signature of the person authorized to act on behalf of the owner of the intellectual property right. An identification of the intellectual property claimed to have been infringed. A detailed description of the material that you claim is infringing, so that we may locate it, including the URL where the infringing material appears. Your address, telephone number, and email address. A statement by you that you have a good faith belief that the allegedly infringing use is not authorized by the intellectual property rights owner, its agent, or the law. A statement, made under penalty of perjury, by you that the above information is accurate and that you are authorized to act on behalf of the owner of the intellectual property rights involved.
  <p>
8.5 Subpoenas Website may be required to disclose information to individuals asserting rights under the DMCA. You hereby authorize Website to release information about you, and/or the materials, data or files uploaded through our site if required by law or subpoena without notice to you, and in accordance with our "Privacy Policy."
  <p>
8.6 Misuse of System Resources Customer shall not misuse system resources including, but not limited to, employing content which consume excessive CPU time or storage space; utilizing excessive bandwidth; or resale of access to content hosted on Website servers.
 <p>
8.7 Other Activities Whether lawful or unlawful, Website reserves the right to determine what is harmful to its User, operations or reputation, including any activities that restrict or inhibit any other User from using and enjoying the Service or the Internet. Please be aware Website reserves the right to cancel any account that is in violation of any of the above policies and revoke Users earnings. If appropriate, Website will refer complaints to law enforcement authorities, and in such case, Website will actively assist law enforcement agencies with the investigation and prosecution of any such activities, including surrendering User account and data information. Complaints about violators of our Policy should be sent via to our abuse department.(admin@ ) Each complaint will be investigated and may result to immediate cancellation of Services without prior notice.
<p>

9. No Warranty You expressly understand and agree that: a) your use of the Service is at your sole risk. Website Services are provided on an "AS IS" and "AS AVAILABLE" basis. Website and its suppliers, to the fullest extent permitted by law, disclaim all warranties, including but not limited to warranties of title, fitness for a particular purpose, merchantability and non-infringement of proprietary or third party rights. Website and its suppliers make no warranties about the accuracy, reliability, completeness, or timeliness of our Services, software, or content b) Website makes no warranty that (1) the Service will meet your requirements (2) the service will be uninterrupted, timely, secure, or error-free, (3) the results that may be obtained from the use of the service will be accurate or reliable, (4) the quality of any products, services, information, or other material purchased or obtained by you through the Service will meet your expectations, and (5) any errors in the software will be corrected c) any material downloaded or otherwise obtained through the use of the Service is done at your own discretion and risk and that you will be solely responsible for any damage to your computer system or loss of data that results from the download of any such material and d) no advice or information, whether oral or written, obtained by you from us or through or from the Service shall create any warranty not expressly stated in these terms and conditions.
 <p>

10. Indemnity You agree to defend, indemnify, and hold harmless Website, its affiliates, officers, directors, employees and agents, from and against any claims, actions or demands, including without limitation reasonable legal fees, alleging or resulting from your use the Service, or your breach of this Agreement or other Website policies, terms and conditions.
 <p>

11. Limitation of Liability Your use of Website is at your own risk. If you are dissatisfied with any aspect of our Service or with these terms & conditions, or any other rules or policies, your sole remedy is to discontinue use of the Service. You expressly understand and agree that Website shall not be liable for any direct, indirect, incidental, special, consequential exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if we have been advised of the possibility of such damages), resulting from: (1) the use or the inability to use the Service (2) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Service; (3) unauthorized access to or alteration of your transmissions or data; (4) statements or conduct of any third party on the service or (5) any other matter relating to the Service. Furthermore, you accept full liability for your actions while using Websites services, and agree that Website is not liable for any damages or legal implications caused by your use or abuse of our services.
  <p>

12. Modifications to Agreements, Rules for Extension of Services We reserve the right to change this Service Agreement at any time without notice. We also reserve the right at any time to modify or discontinue the Service, temporarily or permanently, with or without notice to you. You agree that we shall not be liable to you or any third party for any modification, suspension or discontinuance of the Service. You acknowledge that we may establish general practices and limits concerning use of the Service, including the maximum disk space that will be allotted on Websites servers on your behalf, and the maximum number of times (and the maximum duration for which) you may access the Service in a given period of time. In addition, you recognize that Website has the right, without preliminary prevention, to change tariffs for the utilization of Services. Modification of tariffs for the utilization of Services will take effect after the termination of the validity of an existing subscription of the Client.
<p>

13. Termination Website has the immediate right to issue a warning, suspend, lock out access and operation of Services for User either temporarily or indefinitely, terminate Users account, refuse to provide extension of Services to User and revoke all earnings if: a) Website is justified to believe that the Client has broken or has not executed any aspect of the present Agreement or other contracts or instructions of Website b) Website is unable to verify or authenticate any information User provides to Website and c) Website believes that Users actions may cause legal liability for User, Websites other Users, or Website. Also, Website may in its sole discretion and at any time discontinue providing Services or any part thereof, as well as may terminate any User agreement with or without notice for any reason or no reason at all. Notice of termination will be provided via email and effective on the date set within the email. All legitimate earnings, as determined by Website, will be paid during the next compensation period. You agree that any termination of your access to the Service under any provision of these terms and conditions may be effected without prior notice, and acknowledge and agree that Website may immediately deactivate, archive or delete your account and all related information and data and/or any further access to such data or the Service. Further, you agree that Website shall not be liable to you or any third-party for any termination of your access to Services. Upon termination of this Agreement by either User or Website, all of Customer rights under this Agreement, and Websites provision of Services, will terminate immediately. The Sections 6 ("Customer Data"), 9 ("No Warranty"), 10 ("Indemnity"), 11 ("Limitation Of Liability") and this Section 13 will survive any termination of this Agreement. After the cancellation of the present Agreement by the Client or Website, all privileges of the User stipulated in the Agreement, and obligations of Website extension of Services, are immediately cancelled. Incapacity of Website to undertake actions concerning violations performed by theClient or other persons, does not deprive the right of Website to take measures concerning subsequent or similar violation.
<p>

14. Controlling Law and Jurisdiction These terms and conditions will be governed by and construed in accordance with the laws of the State of New York, excluding that body of law governing conflict of laws. Any legal action or proceeding relating to or arising out of these Terms or your use of the Web site will be brought in a federal or state court in Queens County, New York, and you submit to the venue and personal jurisdiction of such court. If any provision of these Terms is held to be invalid or unenforceable, such provision will be enforced to the greatest extent possible and the remaining provisions will remain in full force and effect. Headings are for reference purposes only and in no way define, limit, construe, or describe the scope or extent of such section. Websites failure to act with respect to a breach by User or others does not waive Websites right to act with respect to subsequent or similar breaches. No action by Customer arising under this Agreement may be brought at any time more than twelve (12) months after the facts occurred upon which the cause of action arose.
 <p>

15. Relationship User and Website are independent contractors, and no agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by this Agreement. All earnings generated by User via Our Site are taxed at Users country. No deductions for taxes of any kind shall be made from any payments paid to User. Payment of all applicable taxes shall be Users sole responsibility.
<p>
16. Spamming Website does not endorse spamming our download links in order to generate downloads and revenue. We take no responsibilty for any damages caused by our users while spamming files and pages hosted on our server. Every user must comply with the spam laws of their area of residence (For example, in the United States, their state laws and the federal laws).
 <p>
17. Miscellaneous. User may not assign any of its rights, or delegate any of its duties, under this Agreement, and any attempted assignment will be null and void. Operation of our Services may be interfered with by numerous factors outside of our control and we shall not be liable to you for any delay or failure in performance under this Agreement resulting directly or indirectly from causes beyond Websites control. If any provision of this Agreement is held to be invalid or unenforceable, that clause should be bypassed, with the least damage of interests of the parties, and the remaining provisions shall be enforced. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. Accepting this agreement, you represent and warrant to Website Company that you are not a competitor of Website and you undertake to not use the information received through the utilization of the website of Website and Services of Website to compete with Website in its business. Except for other agreements or terms appearing on the Web site, this Agreement set forth the entire understanding and agreement between us with respect to the subject matter hereof. does not support or allow uploading files containing illegal content as well as other forms of transferring illegal or obscene materials and information that induce individuals to committing illegal action.
<p>
    
</p>

















<div class="gap20px">&nbsp;</div>

<div class="gap20px">&nbsp;</div>

<div class="gap20px">&nbsp;</div>

<div class="gap20px">&nbsp;</div>





</div>

<!--End Contents-->





{include file="footer.tpl.php"}

